/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculator.h"

bool_t
xdr_Operands (XDR *xdrs, Operands *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->operand1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->operand2))
		 return FALSE;
	return TRUE;
}
