/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Operands {
	double operand1;
	double operand2;
};
typedef struct Operands Operands;

#define CALCULATOR 0x20000001
#define CALCULATOR_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUM 1
extern  double * sum_1(Operands *, CLIENT *);
extern  double * sum_1_svc(Operands *, struct svc_req *);
#define SUBTRACT 2
extern  double * subtract_1(Operands *, CLIENT *);
extern  double * subtract_1_svc(Operands *, struct svc_req *);
#define MULTIPLY 3
extern  double * multiply_1(Operands *, CLIENT *);
extern  double * multiply_1_svc(Operands *, struct svc_req *);
#define DIVIDE 4
extern  double * divide_1(Operands *, CLIENT *);
extern  double * divide_1_svc(Operands *, struct svc_req *);
#define EQUALS 5
extern  char ** equals_1(Operands *, CLIENT *);
extern  char ** equals_1_svc(Operands *, struct svc_req *);
extern int calculator_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUM 1
extern  double * sum_1();
extern  double * sum_1_svc();
#define SUBTRACT 2
extern  double * subtract_1();
extern  double * subtract_1_svc();
#define MULTIPLY 3
extern  double * multiply_1();
extern  double * multiply_1_svc();
#define DIVIDE 4
extern  double * divide_1();
extern  double * divide_1_svc();
#define EQUALS 5
extern  char ** equals_1();
extern  char ** equals_1_svc();
extern int calculator_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Operands (XDR *, Operands*);

#else /* K&R C */
extern bool_t xdr_Operands ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
